spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: debug
